package id.my.gradien.cloud.core.ui.theme
import androidx.compose.ui.graphics.Color

// Light Colors from design.md
val primaryLight = Color(0xFF275022)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3E6837)
val onPrimaryContainerLight = Color(0xFFB5E5A8)
val secondaryLight = Color(0xFF526442)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD2E6BC)
val onSecondaryContainerLight = Color(0xFF576846)
val tertiaryLight = Color(0xFF394949)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF516161)
val onTertiaryContainerLight = Color(0xFFCADCDB)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8FAF9)
val onBackgroundLight = Color(0xFF191C1C)
val surfaceLight = Color(0xFFF8FAF9)
val onSurfaceLight = Color(0xFF191C1C)
val surfaceVariantLight = Color(0xFFE1E3E2)
val onSurfaceVariantLight = Color(0xFF42493F)
val outlineLight = Color(0xFF72796E)
val outlineVariantLight = Color(0xFFC2C9BC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3131)
val inverseOnSurfaceLight = Color(0xFFEFF1F0)
val inversePrimaryLight = Color(0xFFA4D397)
val surfaceDimLight = Color(0xFFD8DADA)
val surfaceBrightLight = Color(0xFFF8FAF9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4F3)
val surfaceContainerLight = Color(0xFFECEEED)
val surfaceContainerHighLight = Color(0xFFE6E9E8)
val surfaceContainerHighestLight = Color(0xFFE1E3E2)

// Dark Colors (Generated/Fallback based on Design Principles if not specified)
// Since design.md doesn't specify dark colors, we'll use a standard dark palette 
// that complements the primary botanical green.
val primaryDark = Color(0xFFA4D397)
val onPrimaryDark = Color(0xFF002201)
val primaryContainerDark = Color(0xFF275022)
val onPrimaryContainerDark = Color(0xFFB5E5A8)
val secondaryDark = Color(0xFFB9CDA4)
val onSecondaryDark = Color(0xFF253518)
val secondaryContainerDark = Color(0xFF3B4C2C)
val onSecondaryContainerDark = Color(0xFFD5E9BF)
val tertiaryDark = Color(0xFFB8CACA)
val onTertiaryDark = Color(0xFF233232)
val tertiaryContainerDark = Color(0xFF3A4A49)
val onTertiaryContainerDark = Color(0xFFD4E6E5)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191C1C)
val onBackgroundDark = Color(0xFFE1E3E2)
val surfaceDark = Color(0xFF191C1C)
val onSurfaceDark = Color(0xFFE1E3E2)
val surfaceVariantDark = Color(0xFF42493F)
val onSurfaceVariantDark = Color(0xFFC2C9BC)
val outlineDark = Color(0xFF8C9387)
val outlineVariantDark = Color(0xFF42493F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E3E2)
val inverseOnSurfaceDark = Color(0xFF2E3131)
val inversePrimaryDark = Color(0xFF275022)
val surfaceDimDark = Color(0xFF191C1C)
val surfaceBrightDark = Color(0xFF3B3F3E)
val surfaceContainerLowestDark = Color(0xFF0E1111)
val surfaceContainerLowDark = Color(0xFF1C1F1F)
val surfaceContainerDark = Color(0xFF202323)
val surfaceContainerHighDark = Color(0xFF2A2D2D)
val surfaceContainerHighestDark = Color(0xFF353838)
